export default defineEventHandler(() => [
  {
    id: "5ff76e76-4fc3-4ba4-8652-1866a8e734zz",
    category: "MERN Stack",
    name: "Lapino",
    slug: "lapino",
    img: "/lp-home.png",
    linkToPage: "https://lapino.onrender.com/",
    linkToSrc: "https://github.com/ZinoChan/lapino",
    description: "E-commerce for Kids products",
    tools: [
      "React",
      "Express",
      "Tailwindcss",
      "Redux",
      "Firebase-admin",
      "Typescript",
    ],
  },
  {
    id: "6a29d826-fbba-4093-8eef-ac3642c79bbf",
    category: "Nextjs",
    name: "Oishi",
    slug: "oishi",
    img: "/oishi.jpg",
    linkToPage: "https://oishi.vercel.app/",
    linkToSrc: "https://github.com/ZinoChan/Oishi",
    description: "fast food order and delivery app",
    tools: [
      "Next js",
      "Redux Toolkit",
      "Redux-persist",
      "Redux Saga",
      "Firebase",
      "Tailwindcss",
    ],
  },
  {
    id: "9f4d390d-1291-4523-8875-3422c0d37ba3",
    category: "React",
    name: "Run",
    slug: "run",
    img: "/run.jpg",
    linkToPage: "https://run-store.vercel.app/",
    linkToSrc: "https://github.com/ZinoChan/Run",
    description: "sneakers ecommerce app",
    tools: ["React", "Redux", "Redux Saga", "Firebase", "Bootstrap"],
  },
  {
    id: "4e701cf5-98a2-4f42-95b5-758cc122d08d",
    category: "Nextjs",
    name: "Animix",
    slug: "animix",
    img: "/orcanime.jpg",
    linkToPage: "https://orcanime.vercel.app/",
    linkToSrc: "https://github.com/ZinoChan/orcanime",
    description: "Anime movies and blog",
    tools: ["Next js", "framer-motion", "tailwindcss", "firebase", "redux"],
  },

  {
    id: "e6b700d5-1110-4de3-8d4f-102aa947437d",
    category: "Gatsbyjs",
    name: "Perfume",
    slug: "perfume",
    img: "/perfume.jpg",
    linkToPage: "https://perfuma.netlify.app/",
    linkToSrc: "https://github.com/ZinoChan/Perfume",
    description: "Perfume landing page",
    tools: ["Gatsby", "Gsap", "tailwindcss", "Styled Components"],
  },
  {
    id: "5ff76e76-4fc3-4ba4-8652-1866a8e734db",
    category: "Gatsbyjs",
    name: "Sushio",
    slug: "sushio",
    img: "/gohan.jpg",
    linkToPage: "https://sushio.netlify.app",
    linkToSrc: "https://github.com/ZinoChan/sushio",
    description: "japanese restaurant booking ",
    tools: ["Gatsby", "gsap", "tailwindcss"],
  },
]);
